// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvrr0S21s9E3Rhy1IRZfQAihY0v84qTE',
    appId: '1:931378336633:web:f1d0e41bfd99200a25d5a8',
    messagingSenderId: '931378336633',
    projectId: 'digital-islamic-hub-29dd5',
    authDomain: 'digital-islamic-hub-29dd5.firebaseapp.com',
    storageBucket: 'digital-islamic-hub-29dd5.firebasestorage.app',
    measurementId: 'G-77NYDD4YFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mT164t0B_XNStogfHewCjOIrgrCriN4',
    appId: '1:931378336633:android:f254010de7275ab425d5a8',
    messagingSenderId: '931378336633',
    projectId: 'digital-islamic-hub-29dd5',
    storageBucket: 'digital-islamic-hub-29dd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflH0h6jtR8AIPEGVxclbWHIr8rLey5KU',
    appId: '1:931378336633:ios:45965002e0f8a0db25d5a8',
    messagingSenderId: '931378336633',
    projectId: 'digital-islamic-hub-29dd5',
    storageBucket: 'digital-islamic-hub-29dd5.firebasestorage.app',
    iosBundleId: 'com.example.digitalIslamicHub',
  );
}
